apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilender-user
  namespace: ilender-ns
  labels:
    app: ilender-application
    subname: user
spec:
  selector:
    matchLabels:
      app: ilender-application
      subname: user
  replicas: 1
  template:
    metadata:
      labels:
        app: ilender-application
        subname: user
    spec:
      containers:
        - name: container-user
          image: "gandigit/ilender-user-demo:0.0.1"
          imagePullPolicy: Always
          ports:
            - name: my-http
              containerPort: 9076
              protocol: TCP
            - name: https
              containerPort: 8082
          # resources:
          #   requests:
          #     memory: "500Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "1024Mi"
          #     cpu: "500m"
          # livenessProbe:
          #   httpGet:
          #     path: /user
          #     port: my-http
          #   initialDelaySeconds: 60
          # failureThreshold: 60
          # readinessProbe:
          #   httpGet:
          #     path: /user
          #     port: my-http
          #   initialDelaySeconds: 60
          env:
            - name: MY_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_CONTAINER_NAME
              value: container-user
            - name: MY_CONTAINER_IMAGE
              value: "gandigit/ilender-user-demo:0.0.1"
            - name: MY_LABELS_APP
              value: userservice
            - name: MY_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: skipExternalLog
              value: "TRUE"                  
          envFrom:
            - configMapRef:
                name: ilender-configmap-urls
            - configMapRef:
                name: ilender-configmap-db
            - configMapRef:
                name: ilender-configmap-mq
            - configMapRef:
                name: ilender-configmap-eventstream
            - configMapRef:
                name: ilender-configmap-common

---
apiVersion: v1
kind: Service
metadata:
  name: ilender-user
  namespace: ilender-ns
  labels:
    app: ilender-application
    subname: user
spec:
  type: LoadBalancer
  ports:
    - name: my-http
      port: 9090
      targetPort: my-http
  selector:
    app: ilender-application
    subname: user

